---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-node

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile" }}
            - v1-bundle-

      - run:
          name: Install gems
          command: |
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3

      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile" }}
          paths:
            - ./vendor/bundle

      - run:
          name: Lint codebase
          command: |
            bundle exec rubocop

      - restore_cache:
          keys:
            - v1-coverage-{{ .Branch }}-

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            COVERAGE=true \
              bundle exec rspec \
                --format progress \
                --format RspecJunitFormatter \
                --out /tmp/test-results/rspec.xml

      - save_cache:
          key: v1-coverage-{{ .Branch }}-{{ epoch }}
          paths:
            - ./coverage

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
